
###删除学院
DELETE http://localhost:8080/api/admin/college/1421292569574539264
Content-Type: application/json


###添加学院
POST http://localhost:8080/api/admin/college
Content-Type: application/json
token: {{token}}

{
"collegeName": "林学院"
}

###更新学院
PUT http://localhost:8080/api/admin/college
Content-Type: application/json

{
  "collegeName": "计算机与控制工程学院1",
  "id": "1421292569574539264"
}


###添加学院管理员
POST http://localhost:8080/api/admin/collegeadmin
Content-Type: application/json
token: {{token}}

{
  "account": "admin1",
  "password": "admin2",
  "collegeId": "1421292569574539264"
}


###删除学院管理员
DELETE http://localhost:8080/api/admin/collegeadmin/1421295925495889920
Content-Type: application/json
token: {{token}}

###重置学员管理员密码
PUT http://localhost:8080/api/admin/resetcollegeadminpassword/admin1
Content-Type: application/json
token: {{token}}




