

###管理员登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
    "account":"admin",
    "password":"admin"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}


###学院管理员登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
  "account":"admin1",
  "password":"admin2"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}



###学生注册
POST http://localhost:8080/api/open/student/register
Content-Type: application/json

{
  "user": {
    "account": "2023211456",
    "password": "Yhm050227",
    "name": "qwe",
    "phone": "18045088469",
    "email": "18045088469@163.com",
    "studentNumber": "2023211486",
    "collegeId": 1421360334259912704,
    "majorId": 1234,
    "categoryId": 13443
  },
  "studentScore": {
    "majorRank": 1,
    "weightedScore": "80"
  }
}

###老师注册
POST http://localhost:8080/api/open/teacher/register
Content-Type: application/json

{
  "account": "2022211486",
  "password": "Yhm050227",
  "name": "杨肃",
  "phone": "18745088469",
  "email": "18745088469@163.com",
  "teacherNumber": "2022211486",
  "collegeId":1426231915943591936
}



###学生登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2023211456",
  "password": "Yhm050227"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}

###教师登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2022211486",
  "password": "Yhm050227"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}

###查找全部学院
GET http://localhost:8080/api/open/colleges
Content-Type: application/json


###查找学院对应大类
GET http://localhost:8080/api/open/categories/1426232357398282240
Content-Type: application/json


###查找全部专业
GET http://localhost:8080/api/open/majors/1426232054179463168
Content-Type: application/json