
###管理员登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
    "account":"admin",
    "password":"admin"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}

###学生注册
POST http://localhost:8080/api/open/student/register
Content-Type: application/json

{
  "account": "2023211486",
  "password": "Yhm050227",
  "name": "杨鸿铭",
  "phone": "18045088469",
  "email": "18045088469@163.com",
  "studentNumber": "2023211486",
  "collegeId": "college_001",
  "majorId": "major_002",
  "categoryId": "category_001"
}

###老师注册
POST http://localhost:8080/api/open/teacher/register
Content-Type: application/json

{
  "account": "2022211486",
  "password": "Yhm050227",
  "name": "杨肃",
  "phone": "18745088469",
  "email": "18745088469@163.com",
  "TeacherNumber": "2022211486",
  "collegeId": "college_001"
}

###学生登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2023211486",
  "password": "Yhm050227"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}

###教师登录
POST http://localhost:8080/api/open/login
Content-Type: application/json

{
  "account": "2022211486",
  "password": "Yhm050227"
}
> {% client.global.set("token", response.headers.valueOf("token")); %}